data:
  raw_data_path: data/brain-tumor-mri

artifacts:
  model_path: models/best_model.pt
  onnx_path: app/models/best_model.onnx

reports:
  image_path: reports/images/batch_visualization.png
  history_path: reports/images/history.png